# Generated by Django 6.0 on 2026-01-01 03:43

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriasModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PedidosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=254)),
                ("precio_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsuariosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("contrasena", models.CharField(max_length=254)),
                ("correo", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("rol", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=50)),
                ("imagen", models.ImageField(upload_to="media/img/productos")),
                ("descripcion", models.TextField(default="")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=10)),
                ("medidas", models.TextField()),
                ("capacidad", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "colores_meta_datos",
                    models.JSONField(
                        default=api.models.ProductosModel.default_color_metadata
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.categoriasmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoProductosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                (
                    "precio_unitario_producto",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pedidosmodel",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productosmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pedidosmodel",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.usuariosmodel"
            ),
        ),
        migrations.CreateModel(
            name="DireccionesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(max_length=100)),
                ("colonia", models.CharField(max_length=100)),
                ("codigo_postal", models.CharField(max_length=50)),
                ("ciudad", models.CharField(max_length=50)),
                ("estado", models.CharField(max_length=50)),
                ("pais", models.CharField(max_length=50)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuariosmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductosFavoritosModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.productosmodel",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuariosmodel",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "producto"),
                        name="uniq_usuario_producto_favorito",
                    )
                ],
            },
        ),
    ]
