# Generated by Django 6.0 on 2026-01-08 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                (
                    "hex",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El color hex debe venir como #RRGGBB, por ejemplo #FFAA00",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "colores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ProductoColorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="color_productos",
                        to="api.colormodel",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producto_colores",
                        to="api.productosmodel",
                    ),
                ),
            ],
            options={
                "db_table": "producto_colores",
                "indexes": [
                    models.Index(
                        fields=["producto"], name="producto_co_product_1165f8_idx"
                    ),
                    models.Index(
                        fields=["color"], name="producto_co_color_i_998030_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("producto", "color"), name="uniq_producto_color"
                    )
                ],
            },
        ),
    ]
