# Generated by Django 6.0 on 2026-01-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_colormodel_productocolormodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosmodel",
            name="colores_meta_datos",
        ),
    ]
