# Generated by Django 6.0 on 2026-01-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_productosmodel_colores_meta_datos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colormodel",
            name="activo",
        ),
    ]
