# Generated by Django 6.0 on 2026-01-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_colormodel_activo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductoColorModel",
            new_name="ProductoVariantesModel",
        ),
        migrations.CreateModel(
            name="ProductosImagenesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="img/products/galeria/")),
                ("orden", models.PositiveIntegerField(default=0)),
                ("es_principal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="api.productosmodel",
                    ),
                ),
                (
                    "variante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="api.productovariantesmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["orden", "id"],
                "indexes": [
                    models.Index(
                        fields=["producto", "variante"],
                        name="api_product_product_4fb615_idx",
                    )
                ],
            },
        ),
    ]
