# Generated by Django 6.0 on 2026-01-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_productocolormodel_productovariantesmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productosmodel",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
    ]
