# Generated by Django 6.0 on 2026-01-19 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_productocolormodel_productovariantesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activo'), ('CONVERTED', 'Convertido')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='color_hex_snapshot',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='color_nombre_snapshot',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='descripcion_snapshot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='imagen_principal_snapshot',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='precio_unitario_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='producto_item_snapshot',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='producto_nombre_snapshot',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='subtotal_linea_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items', to='api.productovariantesmodel'),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='aprobado_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='denegado_razon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.direccionesmodel'),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='estado',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('DENIED', 'Denegado'), ('READY', 'Listo'), ('COMPLETED', 'Completado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='nota_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='nota_worker',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pedidosmodel',
            name='subtotal_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoproductosmodel',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedidoproductosmodel',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproductosmodel',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.pedidosmodel'),
        ),
        migrations.AlterField(
            model_name='pedidoproductosmodel',
            name='precio_unitario_producto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproductosmodel',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productosmodel'),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='pedidoproductosmodel',
            index=models.Index(fields=['pedido'], name='api_pedidop_pedido__aedeea_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoproductosmodel',
            index=models.Index(fields=['variante'], name='api_pedidop_variant_3dc76e_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidosmodel',
            index=models.Index(fields=['cliente', 'estado'], name='api_pedidos_cliente_06ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidosmodel',
            index=models.Index(fields=['estado', 'created_at'], name='api_pedidos_estado_831f86_idx'),
        ),
        migrations.AddField(
            model_name='carritoitemmodel',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrito_items', to='api.productovariantesmodel'),
        ),
        migrations.AddField(
            model_name='carritomodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoitemmodel',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carritomodel'),
        ),
        migrations.AddIndex(
            model_name='carritomodel',
            index=models.Index(fields=['cliente', 'estado'], name='api_carrito_cliente_3a2689_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoitemmodel',
            index=models.Index(fields=['carrito'], name='api_carrito_carrito_248ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoitemmodel',
            index=models.Index(fields=['variante'], name='api_carrito_variant_8afc68_idx'),
        ),
        migrations.AddConstraint(
            model_name='carritoitemmodel',
            constraint=models.UniqueConstraint(fields=('carrito', 'variante'), name='uniq_carrito_variante'),
        ),
    ]
