# Generated by Django 6.0 on 2026-01-19 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_carritoitemmodel_carritomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidosmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
