# Generated by Django 6.0 on 2026-01-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_productosmodel_disponible"),
        ("api", "0007_alter_pedidosmodel_created_at_and_more"),
    ]

    operations = []
