# Generated by Django 6.0 on 2026-01-21 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_merge_20260120_1719"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosmodel",
            name="disponible",
        ),
    ]
