# Generated by Django 6.0 on 2026-01-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_productosmodel_disponible"),
    ]

    operations = [
        migrations.AddField(
            model_name="productosmodel",
            name="disponible",
            field=models.BooleanField(default=True),
        ),
    ]
