# Generated by Django 6.0 on 2026-01-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_usuariosmodel_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariosmodel",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Contraseña"
            ),
        ),
    ]
