# Generated by Django 6.0 on 2026-02-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_usuariosmodel_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosmodel",
            name="categoria",
        ),
        migrations.AddField(
            model_name="productosmodel",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, related_name="productos", to="api.categoriasmodel"
            ),
        ),
    ]
