# Generated by Django 6.0 on 2026-03-04 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_productosmodel_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productosmodel",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos_propios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pedidosmodel",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("APPROVED", "Aprobado"),
                    ("DENIED", "Denegado"),
                    ("READY", "Listo"),
                    ("SHIPPED", "Enviado"),
                    ("COMPLETED", "Completado"),
                    ("CANCELED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
