# Generated by Django 6.0 on 2026-03-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_worker_panel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productosmodel",
            name="item",
        ),
        migrations.AddField(
            model_name="productovariantesmodel",
            name="item",
            field=models.CharField(default="", max_length=50),
        ),
    ]
