# Generated by Django 6.0 on 2026-06-15 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_favoritos_variante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productovariantesmodel',
            options={'ordering': ['color__nombre', 'id']},
        ),
    ]
