# Generated by Django 6.0 on 2026-06-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_variante_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariantesmodel',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
