# Generated by Django 6.0 on 2026-06-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_audit_duplicate_items'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productovariantesmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('item', ''), _negated=True), fields=('producto', 'item'), name='unique_producto_item_when_set'),
        ),
    ]
