# Generated by Django 6.0 on 2026-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_unique_item_per_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmodel',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productovariantesmodel',
            name='codigo_barras',
            field=models.CharField(default='', max_length=30),
        ),
    ]
