# Generated by Django 6.0 on 2026-06-24 01:25

from django.db import migrations, models


def backfill_product_states(apps, schema_editor):
    ProductosModel = apps.get_model('api', 'ProductosModel')
    ProductosModel.objects.filter(disponible=True).update(estado='active')
    ProductosModel.objects.filter(disponible=False).update(estado='draft')


def reverse_backfill_product_states(apps, schema_editor):
    ProductosModel = apps.get_model('api', 'ProductosModel')
    ProductosModel.objects.update(estado='draft')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_unique_item_per_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodel',
            name='estado',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.RunPython(backfill_product_states, reverse_backfill_product_states),
    ]
