# Generated by Django 6.0 on 2026-06-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_productosmodel_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="productovariantesmodel",
            name="codigo_barras",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
