# Generated by Django 6.0 on 2026-06-30 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_productovariantesmodel_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('especial', 'Especial')], default='general', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='categoriasmodel',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_descuentos', to='api.descuentosmodel'),
        ),
        migrations.AddField(
            model_name='productosmodel',
            name='descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_descuentos', to='api.descuentosmodel'),
        ),
    ]
