# Generated by Django 6.0 on 2026-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_descuentosmodel_categoriasmodel_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuentosmodel',
            old_name='cantidad',
            new_name='porcentaje',
        ),
    ]
