# Generated by Django 6.0 on 2026-07-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_cantidad_descuentosmodel_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosmodel',
            name='categorias',
        ),
        migrations.AddField(
            model_name='productosmodel',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='api.categoriasmodel'),
        ),
    ]
