# Generated by Django 6.0 on 2026-07-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_productosmodel_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriasmodel',
            old_name='descuento',
            new_name='descuento_general',
        ),
        migrations.RenameField(
            model_name='productosmodel',
            old_name='descuento',
            new_name='descuento_especial',
        ),
    ]
