# Generated by Django 6.0 on 2026-07-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_descuento_categoriasmodel_descuento_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproductosmodel',
            name='descuento_porcentaje_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
