# Generated by Django 6.0 on 2026-07-17 03:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pedidoproductosmodel_descuento_porcentaje_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosmodel',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
