# Generated by Django 6.0 on 2026-07-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_pedidoproductosmodel_descuento_porcentaje_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerOfertaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], max_length=10)),
                ('archivo', models.FileField(upload_to='img/banner-ofertas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
