# Generated by Django 6.0 on 2026-07-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_pedidosmodel_public_id'),
        ('api', '0029_bannerofertamodel'),
    ]

    operations = [
    ]
