# Generated by Django 6.0 on 2026-07-27

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_merge_20260724_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidosmodel",
            name="comprobante_pago",
            field=models.FileField(blank=True, null=True, upload_to=api.models.get_comprobante_path),
        ),
    ]
