# Generated by Django 6.0 on 2026-07-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20260724_1529'),
        ('api', '0030_merge_20260724_1748'),
    ]

    operations = [
    ]
