# Generated by Django 6.0 on 2026-07-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20260724_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
