# Generated by Django 5.2.16 on 2026-07-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_usuariosmodel_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosmodel',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuariosmodel',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
