# Generated by Django 5.2.16 on 2026-07-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_pedidosmodel_comprobante_pago'),
        ('api', '0033_usuariosmodel_verification_code_and_more'),
    ]

    operations = [
    ]
