# Generated by Django 5.2.16 on 2026-07-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20260730_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmodel',
            name='comprobante_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
