# Generated by Django 5.2.16 on 2026-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_comprobante_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosmodel',
            name='requiere_reembolso',
            field=models.BooleanField(default=False),
        ),
    ]
