# Generated by Django 5.2.16 on 2026-08-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_requiere_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosmodel',
            name='vistas',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
