# Generated by Django 6.0 on 2026-08-17 02:52

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_productosmodel_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionesmodel',
            name='calle',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionesmodel',
            name='ciudad',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionesmodel',
            name='codigo_postal',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionesmodel',
            name='colonia',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionesmodel',
            name='estado',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='direccionesmodel',
            name='pais',
            field=api.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariosmodel',
            name='apellido',
            field=api.fields.EncryptedCharField(default='', max_length=255, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='usuariosmodel',
            name='nombre',
            field=api.fields.EncryptedCharField(default='', max_length=255, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='usuariosmodel',
            name='telefono',
            field=api.fields.EncryptedCharField(max_length=255, verbose_name='Teléfono'),
        ),
    ]
