# Generated by Django 6.0 on 2026-08-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_direccionesmodel_calle_and_more'),
        ('api', '0038_worker_role_and_permissions'),
    ]

    operations = [
    ]
