# Generated by Django 5.2.16 on 2026-08-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_direccionesmodel_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosmodel',
            name='peso',
            field=models.CharField(default='', max_length=100),
        ),
    ]
