# Generated by Django 5.2.16 on 2026-08-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_productosmodel_peso'),
        ('api', '0039_merge_20260816_2318'),
    ]

    operations = [
    ]
